Vagrant.configure("2") do |config|
  # Base operating-system image.
  config.vm.box = "cloud-image/debian-13"
  config.vm.box_version = "20260831.2587.0"
  config.vm.box_architecture = "amd64"

    # Disable the default shared folder.
    config.vm.synced_folder ".", "/vagrant", disabled: true

    # Settings shared by both machines.
    config.vm.provider "libvirt" do |libvirt|
        libvirt.uri = "qemu:///system"
        libvirt.driver = "kvm"
        libvirt.memory = 2048
        libvirt.cpus = 2

        # UEFI firmware code.
        libvirt.loader = "/usr/share/OVMF/OVMF_CODE_4M.fd"
    end

    # K3s server machine.
    config.vm.define "ayelasefS" do |server|
        server.vm.hostname = "ayelasefS"
        server.vm.network "private_network",
            ip: "192.168.56.110"

        server.vm.provider "libvirt" do |libvirt|
            libvirt.nvram = "/var/lib/libvirt/qemu/nvram/p1_ayelasefS_VARS.fd"
        end
    end

    # K3s worker machine.
    config.vm.define "ayelasefSW" do |worker|
        worker.vm.hostname = "ayelasefSW"
        worker.vm.network "private_network",
            ip: "192.168.56.111"

        worker.vm.provider "libvirt" do |libvirt|
            libvirt.nvram = "/var/lib/libvirt/qemu/nvram/p1_ayelasefSW_VARS.fd"
        end
    end
end
